In [43]:
import numpy as np

In [44]:
x = np.arange(20)

In [45]:
sws = 4
for i in range(len(x)-sws+1):
    print(x[i:i+sws])

[0 1 2 3]
[1 2 3 4]
[2 3 4 5]
[3 4 5 6]
[4 5 6 7]
[5 6 7 8]
[6 7 8 9]
[ 7  8  9 10]
[ 8  9 10 11]
[ 9 10 11 12]
[10 11 12 13]
[11 12 13 14]
[12 13 14 15]
[13 14 15 16]
[14 15 16 17]
[15 16 17 18]
[16 17 18 19]


In [46]:
(x >= 10) & (x <= 14)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [47]:
y = ((x >= 10) & (x <= 14)).astype(int)

In [48]:
for i in range(len(x)-sws+1):
    print(x[i:i+sws], '\t\t', y[i+sws-1])

[0 1 2 3] 		 0
[1 2 3 4] 		 0
[2 3 4 5] 		 0
[3 4 5 6] 		 0
[4 5 6 7] 		 0
[5 6 7 8] 		 0
[6 7 8 9] 		 0
[ 7  8  9 10] 		 1
[ 8  9 10 11] 		 1
[ 9 10 11 12] 		 1
[10 11 12 13] 		 1
[11 12 13 14] 		 1
[12 13 14 15] 		 0
[13 14 15 16] 		 0
[14 15 16 17] 		 0
[15 16 17 18] 		 0
[16 17 18 19] 		 0


In [49]:
for i in range(len(x)-sws+1):
    print(i, '\t', x[i:i+sws], '\t\t', y[i+sws-1])

0 	 [0 1 2 3] 		 0
1 	 [1 2 3 4] 		 0
2 	 [2 3 4 5] 		 0
3 	 [3 4 5 6] 		 0
4 	 [4 5 6 7] 		 0
5 	 [5 6 7 8] 		 0
6 	 [6 7 8 9] 		 0
7 	 [ 7  8  9 10] 		 1
8 	 [ 8  9 10 11] 		 1
9 	 [ 9 10 11 12] 		 1
10 	 [10 11 12 13] 		 1
11 	 [11 12 13 14] 		 1
12 	 [12 13 14 15] 		 0
13 	 [13 14 15 16] 		 0
14 	 [14 15 16 17] 		 0
15 	 [15 16 17 18] 		 0
16 	 [16 17 18 19] 		 0


In [50]:
z = list('abcdefghijklmnopqrst')

In [51]:
for i in range(len(x)-sws+1):
    print(x[i:i+sws], '\t\t', y[i+sws-1], '\t\t', z[i+sws-1])

[0 1 2 3] 		 0 		 d
[1 2 3 4] 		 0 		 e
[2 3 4 5] 		 0 		 f
[3 4 5 6] 		 0 		 g
[4 5 6 7] 		 0 		 h
[5 6 7 8] 		 0 		 i
[6 7 8 9] 		 0 		 j
[ 7  8  9 10] 		 1 		 k
[ 8  9 10 11] 		 1 		 l
[ 9 10 11 12] 		 1 		 m
[10 11 12 13] 		 1 		 n
[11 12 13 14] 		 1 		 o
[12 13 14 15] 		 0 		 p
[13 14 15 16] 		 0 		 q
[14 15 16 17] 		 0 		 r
[15 16 17 18] 		 0 		 s
[16 17 18 19] 		 0 		 t


In [52]:
y_la = np.array([y[i+sws-1] for i in range(len(y)-sws +1)])

In [53]:
x_la = np.array([x[i: i+sws] for i in range(len(x)-sws +1)])

In [54]:
for i in range(len(y_la)-sws+1):
    print(y_la[i:i+sws])

[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 1]
[0 0 1 1]
[0 1 1 1]
[1 1 1 1]
[1 1 1 1]
[1 1 1 0]
[1 1 0 0]
[1 0 0 0]
[0 0 0 0]
[0 0 0 0]


In [55]:
for i in range(len(y_la)-sws+1):
    print(x_la[i:i+sws], '\t\t', y_la[i:i+sws])

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]] 		 [0 0 0 0]
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]] 		 [0 0 0 0]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 		 [0 0 0 0]
[[3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 		 [0 0 0 0]
[[ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]] 		 [0 0 0 1]
[[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]] 		 [0 0 1 1]
[[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]] 		 [0 1 1 1]
[[ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]] 		 [1 1 1 1]
[[ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]] 		 [1 1 1 1]
[[ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]] 		 [1 1 1 0]
[[10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]] 		 [1 1 0 0]
[[11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]] 		 [1 0 0 0]
[[12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]] 		 [0 0 0 0]
[[13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]
 [16 17 18 19]] 		 [0 0 0 0]


In [56]:
for i in range(len(y_la)-sws+1):
    print(x_la[i:i+sws], '\t\t', y_la[i:i+sws])

[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]] 		 [0 0 0 0]
[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]] 		 [0 0 0 0]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]] 		 [0 0 0 0]
[[3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]] 		 [0 0 0 0]
[[ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]] 		 [0 0 0 1]
[[ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]] 		 [0 0 1 1]
[[ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]] 		 [0 1 1 1]
[[ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]] 		 [1 1 1 1]
[[ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]] 		 [1 1 1 1]
[[ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]] 		 [1 1 1 0]
[[10 11 12 13]
 [11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]] 		 [1 1 0 0]
[[11 12 13 14]
 [12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]] 		 [1 0 0 0]
[[12 13 14 15]
 [13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]] 		 [0 0 0 0]
[[13 14 15 16]
 [14 15 16 17]
 [15 16 17 18]
 [16 17 18 19]] 		 [0 0 0 0]
